title: nlowy-snhu homepage
description: GitHub Pages ePortfolio for CS 499

markdown: GFM
# Original theme used remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
